create table if not exists profiles (
  token_id text primary key,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

alter table profiles enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'profiles'
      and policyname = 'profiles_select_all'
  ) then
    create policy profiles_select_all
      on profiles
      for select
      to anon, authenticated
      using (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'profiles'
      and policyname = 'profiles_insert_all'
  ) then
    create policy profiles_insert_all
      on profiles
      for insert
      to anon, authenticated
      with check (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'profiles'
      and policyname = 'profiles_update_all'
  ) then
    create policy profiles_update_all
      on profiles
      for update
      to anon, authenticated
      using (true)
      with check (true);
  end if;
end
$$;

create table if not exists collections (
  id bigint generated by default as identity primary key,
  collector_address text not null,
  collector_name text not null,
  profile_id text not null,
  tx_hash text not null,
  created_at timestamptz not null default now()
);

alter table collections enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'collections'
      and policyname = 'collections_select_all'
  ) then
    create policy collections_select_all
      on collections
      for select
      to anon, authenticated
      using (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'collections'
      and policyname = 'collections_insert_all'
  ) then
    create policy collections_insert_all
      on collections
      for insert
      to anon, authenticated
      with check (true);
  end if;
end
$$;

create index if not exists idx_collections_collector_address
  on collections (collector_address);

create table if not exists app_stats (
  id int primary key,
  minted int not null default 0,
  collections int not null default 0,
  live_tx int not null default 0,
  last_identity_block bigint not null default 0,
  last_collection_block bigint not null default 0,
  updated_at timestamptz not null default now()
);

alter table app_stats enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'app_stats'
      and policyname = 'app_stats_select_all'
  ) then
    create policy app_stats_select_all
      on app_stats
      for select
      to anon, authenticated
      using (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'app_stats'
      and policyname = 'app_stats_insert_all'
  ) then
    create policy app_stats_insert_all
      on app_stats
      for insert
      to anon, authenticated
      with check (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'app_stats'
      and policyname = 'app_stats_update_all'
  ) then
    create policy app_stats_update_all
      on app_stats
      for update
      to anon, authenticated
      using (true)
      with check (true);
  end if;
end
$$;

insert into app_stats (id, minted, collections, live_tx, last_identity_block, last_collection_block)
values (1, 0, 0, 0, 0, 0)
on conflict (id) do nothing;

create or replace function leaderboard_top_collectors(top_n int default 20)
returns table (
  username text,
  address text,
  total_collected bigint
)
language sql
stable
as $$
  select
    c.collector_name as username,
    c.collector_address as address,
    count(*) as total_collected
  from collections c
  group by c.collector_name, c.collector_address
  order by total_collected desc, max(c.created_at) desc
  limit top_n;
$$;

create table if not exists live_locations (
  wallet_address text primary key,
  display_name text not null,
  profile_id text,
  latitude double precision not null,
  longitude double precision not null,
  avatar text not null,
  networking_until timestamptz not null default (now() + interval '45 minutes'),
  updated_at timestamptz not null default now()
);

create index if not exists idx_live_locations_updated_at
  on live_locations (updated_at desc);

alter table live_locations enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'live_locations'
      and policyname = 'live_locations_select_all'
  ) then
    create policy live_locations_select_all
      on live_locations
      for select
      to anon, authenticated
      using (true);
  end if;
end
$$;

create table if not exists encounter_waves (
  id bigint generated by default as identity primary key,
  from_wallet text not null,
  to_wallet text not null,
  from_name text not null,
  profile_id text,
  status text not null default 'pending',
  created_at timestamptz not null default now()
);

create index if not exists idx_encounter_waves_to_wallet
  on encounter_waves (to_wallet, status, created_at desc);

alter table encounter_waves enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'encounter_waves'
      and policyname = 'encounter_waves_select_all'
  ) then
    create policy encounter_waves_select_all
      on encounter_waves
      for select
      to anon, authenticated
      using (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'encounter_waves'
      and policyname = 'encounter_waves_insert_all'
  ) then
    create policy encounter_waves_insert_all
      on encounter_waves
      for insert
      to anon, authenticated
      with check (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'encounter_waves'
      and policyname = 'encounter_waves_update_all'
  ) then
    create policy encounter_waves_update_all
      on encounter_waves
      for update
      to anon, authenticated
      using (true)
      with check (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'live_locations'
      and policyname = 'live_locations_insert_all'
  ) then
    create policy live_locations_insert_all
      on live_locations
      for insert
      to anon, authenticated
      with check (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'live_locations'
      and policyname = 'live_locations_update_all'
  ) then
    create policy live_locations_update_all
      on live_locations
      for update
      to anon, authenticated
      using (true)
      with check (true);
  end if;
end
$$;
