create table if not exists profiles (
  token_id text primary key,
  payload jsonb not null,
  created_at timestamptz not null default now()
);

create table if not exists collections (
  id bigint generated by default as identity primary key,
  collector_address text not null,
  collector_name text not null,
  profile_id text not null,
  tx_hash text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_collections_collector_address
  on collections (collector_address);

create table if not exists app_stats (
  id int primary key,
  minted int not null default 0,
  collections int not null default 0,
  live_tx int not null default 0,
  last_identity_block bigint not null default 0,
  last_collection_block bigint not null default 0,
  updated_at timestamptz not null default now()
);

insert into app_stats (id, minted, collections, live_tx, last_identity_block, last_collection_block)
values (1, 0, 0, 0, 0, 0)
on conflict (id) do nothing;

create or replace function leaderboard_top_collectors(top_n int default 20)
returns table (
  username text,
  address text,
  total_collected bigint
)
language sql
stable
as $$
  select
    c.collector_name as username,
    c.collector_address as address,
    count(*) as total_collected
  from collections c
  group by c.collector_name, c.collector_address
  order by total_collected desc, max(c.created_at) desc
  limit top_n;
$$;

create table if not exists live_locations (
  wallet_address text primary key,
  display_name text not null,
  profile_id text,
  latitude double precision not null,
  longitude double precision not null,
  avatar text not null,
  updated_at timestamptz not null default now()
);

create index if not exists idx_live_locations_updated_at
  on live_locations (updated_at desc);

alter table live_locations enable row level security;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'live_locations'
      and policyname = 'live_locations_select_all'
  ) then
    create policy live_locations_select_all
      on live_locations
      for select
      to anon, authenticated
      using (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'live_locations'
      and policyname = 'live_locations_insert_all'
  ) then
    create policy live_locations_insert_all
      on live_locations
      for insert
      to anon, authenticated
      with check (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public'
      and tablename = 'live_locations'
      and policyname = 'live_locations_update_all'
  ) then
    create policy live_locations_update_all
      on live_locations
      for update
      to anon, authenticated
      using (true)
      with check (true);
  end if;
end
$$;
